version: "3.1"

services:
  db:
    container_name: foundry-web-app-tests-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foundry
    ports:
      # Non-standard postgres port to avoid collisions
      - "8765:5432"
